// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Models.Models;
using System;
using System.Collections.Generic;

namespace Models.Models.Configurations
{
    public partial class BeerConfiguration : IEntityTypeConfiguration<Beer>
    {
        public void Configure(EntityTypeBuilder<Beer> entity)
        {
            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.BeerName)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("beerName");

            entity.Property(e => e.BeerStyle)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("beerStyle");

            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("price");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Beer> entity);
    }
}
