// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Models.Models;
using System;
using System.Collections.Generic;

namespace Models.Models.Configurations
{
    public partial class OrdersConfiguration : IEntityTypeConfiguration<Orders>
    {
        public void Configure(EntityTypeBuilder<Orders> entity)
        {
            entity.HasKey(e => new { e.Id, e.IdUser, e.IdBeer })
                .HasName("PK__Orders__98EB1F76FD9F7246");

            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.IdUser).HasColumnName("id_User");

            entity.Property(e => e.IdBeer).HasColumnName("id_Beer");

            entity.Property(e => e.Quantity).HasColumnName("quantity");

            entity.Property(e => e.SubTotal).HasColumnName("sub_Total");

            entity.HasOne(d => d.IdBeerNavigation)
                .WithMany(p => p.Orders)
                .HasForeignKey(d => d.IdBeer)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__id_Beer__46E78A0C");

            entity.HasOne(d => d.IdUserNavigation)
                .WithMany(p => p.Orders)
                .HasForeignKey(d => d.IdUser)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__id_User__45F365D3");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Orders> entity);
    }
}
