// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class Beer
    {
        public Beer()
        {
            Orders = new HashSet<Orders>();
        }

        public int Id { get; set; }
        public string BeerName { get; set; } = null!;
        public string BeerStyle { get; set; } = null!;
        public decimal Price { get; set; } = 0!;

        public virtual ICollection<Orders> Orders { get; set; }
    }
}