// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class Orders
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdBeer { get; set; }
        public int Quantity { get; set; }
        public int SubTotal { get; set; }

        public virtual Beer IdBeerNavigation { get; set; }
        public virtual Users IdUserNavigation { get; set; }
    }
}